version: '2'
services:
  zookeeper:
    image: zookeeper:3.4.13
    container_name: zookeeper
    restart: always
    #ports:
    #  - 2181:2181
    expose: 
       - "2182"
    networks:
      saturn-network: 
        ipv4_address: 172.19.0.4
networks:
  saturn-network:
    external: true
