version: '3.3'
#https://docs.docker.com/samples/library/mysql

services:
  db:
    container_name: saturn-db
    image: pjsong/saturn-db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "${port:-8305}:3306"  
    environment:
      MYSQL_DATABASE: saturn_console
      # docker-compose up pwd=xxx, pwd:-defaultpass use defaultpsss if variable is empty or unset
      MYSQL_ROOT_PASSWORD: ${pwd:-defaultpass}
    volumes:
      - saturn_db:/var/lib/mysql      
    networks:
      omd-network: 
        ipv4_address: 172.19.0.2

networks:
  omd-network:
    external: true

volumes:
    saturn_db:     