version: '2'
#https://docs.docker.com/samples/library/mysql
#pwd=pengeldotcN8 port=8305 ip=172.19.0.2 docker-compose up -d
# no default value, problem

services:
  db:
    container_name: saturn-db
    image: pjsong/saturn-db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "${port}:3306"
    environment:
      MYSQL_DATABASE: saturn_console
      # docker-compose up pwd=xxx, pwd:-defaultpass use defaultpsss if variable is empty or unset
      MYSQL_ROOT_PASSWORD: ${pwd}
    volumes:
      - saturn_db:/var/lib/mysql
    networks:
      saturn-network:
        ipv4_address: ${ip}

networks:
  saturn-network:
    external: true

volumes:
  saturn_db: